apiVersion: apps/v1
kind: Deployment
metadata:
  name: jishnu-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jishnu-springboot
  template:
    metadata:
      labels:
        app: jishnu-springboot
    spec:
      containers:
        - name: springboot
          image: jishnucj/jishnucj-docker-demo-test2:jishnucj-docker-demo-test2
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jishnu-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jishnu-springboot
